### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by houjunlin** [MediaBrain-SJTU/K-Diag#1]
Dear author,
I am really interested in your excellent work about K-diag, so I'd like to know when the relevant code and pretrained model will be released? Looking forward to your reply. Many thanks!

**Comment by chaoyi-wu** [comment]
Thanks a lot for your attention. We have released all codes and guidances. Since I am indeed quite busy recently, the codes are not polished carefully and you can drop me e-mails any time if having any problem :)

**Comment by houjunlin** [comment]
Thank you so much for your time and effort you put into releasing the code! It must be very helpful to me in further search.
